### ISSUE TITLE
Adding parvaj AUR package 

### ISSUE THREAD

**Issue by mkoushan** [machitgarha/parvaj#7]
I created [parvaj-bin](https://aur.archlinux.org/packages/parvaj-bin) package in AUR which uses AppImage version of parvaj. Please consider adding it to README.md

**Comment by machitgarha** [comment]
Great!

As you put the effort on such a great thing, it would be better to change README.md yourself. Would you create a PR for that, or should I do it instead?

P.S.: Sorry for my late reply!

**Comment by machitgarha** [comment]
I moved the installation method into the installation.md file, and added a link to it in README.md. So I'm closing this.

Thanks a lot.
